name: e2e

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup playwright
        run: npx playwright install --with-deps

      - name: Waiting for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: shinypoems
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60

      - name: Run E2E test
        run: |
          pnpm run test:e2e
        env:
          PREVIEW_URL: ${{ steps.shinypoems.outputs.url }}

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-e2e
          path: playwright-report/
          retention-days: 30
